export const getApiControl = (state) => state.apiControl;
export const getTasksSelector = (state) => state.tasks.tasks;
export const getTasksRejectedSelector = (state) => state.tasks.tasks['tasksRejected'];
export const getTasksCancelledSelector = (state) => state.tasks.tasks['tasksCancelled'];
export const getTasksInitialisedStatus = (state) => (state.tasks.initialised && state.tasksRejectedCancelled.initialised);
export const getWhoami = (state) => state.whoami.user;
export const getRoleView = (state) => state.roleView;
export const getUsersSelector = (state) => state.users.users;
export const getActiveTaskSelector = (state) => state.task.task;
export const getPresetLocations = (state) => state.availableLocations.locations;
export const availableDeliverablesSelector = (state) => state.availableDeliverables.deliverables;
export const deliverablesSelector = (state) => state.deliverables.deliverables;
