/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingCodeRouteImport } from './routes/$trackingCode'
import { Route as IndexRouteImport } from './routes/index'

const TrackingCodeRoute = TrackingCodeRouteImport.update({
  id: '/$trackingCode',
  path: '/$trackingCode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$trackingCode': typeof TrackingCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$trackingCode': typeof TrackingCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$trackingCode': typeof TrackingCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$trackingCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$trackingCode'
  id: '__root__' | '/' | '/$trackingCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrackingCodeRoute: typeof TrackingCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$trackingCode': {
      id: '/$trackingCode'
      path: '/$trackingCode'
      fullPath: '/$trackingCode'
      preLoaderRoute: typeof TrackingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrackingCodeRoute: TrackingCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
