name: Deploy CDK and Amplify

on:
  push:
    branches:
      - 'production/**'
      - 'test/**'
      - 'dev/**'
      - 'pr/**'

concurrency:
  group: deploy-${{ github.ref_name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      ## SETUP
      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
      - name: 'Install CDK CLI'
        run: npm install -g aws-cdk
      - name: 'Install dependencies'
        working-directory: cdk
        run: npm install
      - name: 'Install Amplify dependencies'
        working-directory: amplify/backend
        run: yarn --frozen-lockfile
      - name: 'npm install front-end'
        run: npm install
      - name: build graphql package
        run: npm run build:simple --workspace @platelet-app/graphql
        ## TESTS
      - name: 'Test cdk functions'
        run: npm run test:cdk-lambda
      - name: 'Test amplify functions'
        run: npm run test:lambda
      - name: 'Test front-end'
        run: npm test -- --silent
      ## AMPLIFY
      - name: 'Get the branch to see if it exists'
        id: branch_check
        run: |
          set +e
          aws amplify get-branch --app-id ${{ vars.AMPLIFY_APP_ID }} --branch-name ${{ github.ref_name }}
          echo "branch_not_exists=$?" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: 'Create the branch if not exists'
        if: ${{ steps.branch_check.outputs.branch_not_exists != '0' }}
        run: aws amplify create-branch --app-id ${{ vars.AMPLIFY_APP_ID }} --branch-name ${{ github.ref_name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: 'Disable auto-build on the branch'
        run: |
          aws amplify update-branch --app-id ${{ vars.AMPLIFY_APP_ID }} --branch-name ${{ github.ref_name }} --no-enable-auto-build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: 'Start initial Amplify build to create the backend environment'
        if: ${{ steps.branch_check.outputs.branch_not_exists != '0' }}
        run: |
          aws amplify start-job --app-id ${{ vars.AMPLIFY_APP_ID }} --branch-name ${{ github.ref_name }} --job-type RELEASE --commit-id ${{ github.sha }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      ## BUILD CDK
      - name: 'Build'
        working-directory: cdk
        run: npm run build
      - name: 'Build lambda functions'
        working-directory: cdk
        run: npm run build-functions
      ## AMPLIFY OUTPUTS
      - name: 'Wait for initial Amplify build if first run'
        if: ${{ steps.branch_check.outputs.branch_not_exists != '0' }}
        uses: duckbytes/amplify-build-status@master
        with:
          app-id: ${{ vars.AMPLIFY_APP_ID }}
          branch-name: ${{ github.ref_name }}
          commit-id: ${{ github.sha }}
          wait: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: 'Get Amplify outputs'
        uses: duckbytes/amplify-get-outputs@master
        id: amplify_outputs
        with:
          app-id: ${{ vars.AMPLIFY_APP_ID }}
          branch-name: ${{ github.ref_name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      ## DEPLOY CDK
      - name: 'Bootstrap and deploy'
        working-directory: cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOY_ENV: ${{ github.ref_name }}
          AWS_ACCOUNT_NUMBER: ${{ vars.AWS_ACCOUNT_NUMBER }}
        run: |
          CONTEXT_ARGS="--context appsyncId=${{ steps.amplify_outputs.outputs.appsync_id }} \
                      --context userPoolId=${{ steps.amplify_outputs.outputs.user_pool_id }} \
                      --context userPoolArn=${{ steps.amplify_outputs.outputs.user_pool_arn }} \
                      --context amplifyEnv=${{ steps.amplify_outputs.outputs.env_name }} \
                      --context graphQLEndpoint=${{ steps.amplify_outputs.outputs.graphql_endpoint }} \
                      --context bucketName=${{ steps.amplify_outputs.outputs.bucket_name }} \
                      --context createCypressTestingRole=${{ startsWith(github.ref_name, 'test/') || startsWith(github.ref_name, 'dev/') || startsWith(github.ref_name, 'pr/') }} \
                      --context alertEmail=${{ vars.ALERT_EMAIL }} \
                      --context fromEmail=${{ vars.FROM_EMAIL }} \
                      --context domainName=${{ vars.DOMAIN_NAME }} "
          npm run bootstrap -- $CONTEXT_ARGS
          npm run deploy -- --require-approval never $CONTEXT_ARGS --outputs-file cdk-out.json
      - name: "Write lambda function roles to custom-roles.json"
        run: |
          ./scripts/get-cdk-roles.sh cdk/cdk-out.json
      - name: "Commit changes"
        id: 'commit_changes'
        uses: EndBug/add-and-commit@v10
        with:
          add: '["./amplify/*custom-roles.json", "./amplify/*custom-policies.json"]'
          default_author: github_actor
          pathspec_error_handling: "exitImmediately"
      ## REBUILD AMPLIFY WITH CDK
      - name: 'Start Amplify build'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          aws amplify start-job --app-id ${{ vars.AMPLIFY_APP_ID }} --branch-name ${{ github.ref_name }} --job-type RELEASE --commit-id ${{ steps.commit_changes.outputs.commit_long_sha || github.sha }}
      - name: Wait for Amplify to finish remote build
        uses: duckbytes/amplify-build-status@master
        with:
          app-id: ${{ vars.AMPLIFY_APP_ID }}
          branch-name: ${{ github.ref_name }}
          commit-id: ${{ steps.commit_changes.outputs.commit_long_sha || github.sha }}
          wait: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      ## UPDATE TENANT API
      - name: Install Amplify CLI and pull project
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          npm install -g @aws-amplify/cli @babel/cli --unsafe-perm=true
          npm install --save-dev @babel/plugin-transform-modules-commonjs
          amplify pull --appId ${{ vars.AMPLIFY_APP_ID }} --envName ${{ steps.amplify_outputs.outputs.env_name }} -y
          babel --plugins @babel/plugin-transform-modules-commonjs src/aws-exports.js > src/aws-exports-es5.js
      - name: Update the tenant API
        if: ${{ vars.API_URL != '' && vars.TENANT_NAME != '' }}
        uses: platelet-app/update-tenant-api-action@main
        with:
          awsEnvName: ${{ steps.amplify_outputs.outputs.env_name }}
          awsExportsFilepath: ${{ github.workspace }}/src/aws-exports-es5.js
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsRegion: ${{ vars.AWS_REGION }}
          apiURL: ${{ vars.API_URL }}
          amplifyEnvName: ${{ steps.amplify_outputs.outputs.env_name }}
          tenantName: ${{ vars.TENANT_NAME }}
      ## CYPRESS TESTS
      - name: Run Cypress tests
        if: ${{ startsWith(github.ref_name, 'test/') || startsWith(github.ref_name, 'dev/') || startsWith(github.ref_name, 'pr/') }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          CYPRESS_bucket: ${{ steps.amplify_outputs.outputs.bucket_name }}
          CYPRESS_userPoolId: ${{ steps.amplify_outputs.outputs.user_pool_id }}
          CYPRESS_clientId: ${{ steps.amplify_outputs.outputs.client_id }}
          CYPRESS_appsyncGraphqlEndpoint: ${{ steps.amplify_outputs.outputs.graphql_endpoint }}
          CYPRESS_appsyncRegion: ${{ vars.AWS_REGION }}
          CYPRESS_appsyncAuthenticationType: AMAZON_COGNITO_USER_POOLS
        run: npx cypress run
