name: Deploy supporting CDK

on:
  push:
    branches:
      - 'production/**'
      - 'test/**'
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install CDK CLI'
        run: npm install -g aws-cdk
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
      - name: 'Install dependencies'
        run: npm install
      - name: 'Build'
        run: npm run build
      - name: 'Build lambda functions'
        run: npm run build-functions
      - name: 'Get Amplify outputs'
        uses: duckbytes/amplify-get-outputs@master
        with:
          app-id: ${{ vars.AMPLIFY_APP_ID }}
          env-name: ${{ vars.AMPLIFY_ENV_NAME || github.ref_name }}
        id: amplify_outputs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: 'Bootstrap and deploy'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOY_ENV: ${{ github.ref_name }}
        run: |
          npm run bootstrap
          npm run deploy -- --require-approval never \
          --context appsyncId=${{ steps.amplify_outputs.outputs.appsync_id }} \
          userPoolId={{ steps.amplify_outputs.outputs.user_pool_id }} \
          graphQLEndpoint={{ steps.amplify_outputs.outputs.graphql_endpoint }} \
          bucketName={{ steps.amplify_outputs.outputs.bucket_name }}

