name: Deploy supporting CDK

on:
  push:
    branches:
      - 'production'
      - 'test'
      - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install CDK CLI'
        run: npm install -g aws-cdk
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
      - name: 'Install dependencies'
        run: npm install
      - name: 'Build'
        run: npm run build
      - name: 'Bootstrap and deploy'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ${{ vars.AWS_REGION }}
          DEPLOY_ENV: ${{ github.ref_name }}
        run: |
          npm run bootstrap
          npm run deploy

