name: Update tenant API

on:
  push:
    branches:
      - 'production/**'
      - 'test/**'
  workflow_dispatch:
    inputs:
      wait_for_amplify:
        description: 'Wait for Amplify build'
        required: true
        default: true
        type: choice
        options:
          - true
          - false
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Wait for Amplify to finish remote build
      uses: duckbytes/amplify-build-status@master
      with:
        app-id: ${{ secrets.AMPLIFY_APP_ID }}
        branch-name: ${{ github.ref_name }}
        commit-id: ${{ github.sha }}
        wait: ${{ github.event_name == 'workflow_dispatch' && inputs.wait_for_amplify || true }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - name: Install Amplify CLI and pull project
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        npm install -g @aws-amplify/cli@10.8 @babel/cli --unsafe-perm=true
        npm install --save-dev @babel/plugin-transform-modules-commonjs
        amplify pull --appId ${{ secrets.AMPLIFY_APP_ID }} --envName ${{ secrets.AMPLIFY_ENV_NAME }} -y
        babel --plugins @babel/plugin-transform-modules-commonjs src/aws-exports.js > src/aws-exports-es5.js
    - name: Update the tenant API
      uses: platelet-app/update-tenant-api-action@main
      with:
        awsEnvName: ${{ secrets.AMPLIFY_ENV_NAME }}
        awsExportsFilepath: ${{ github.workspace }}/src/aws-exports-es5.js
        awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
        awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        awsRegion: ${{ secrets.AWS_REGION }}
        apiURL: ${{ secrets.API_URL }}
        amplifyEnvName: ${{ secrets.AMPLIFY_ENV_NAME }}
        tenantName: ${{ vars.TENANT_NAME }}
